(*
 This document describes version range syntax,
 using the ABNF format (defined in RFC 5234
 -- http://www.ietf.org/rfc/rfc5234.txt).
*)

range_set  = range, { logical_or, range };

(*
r"\s*\|\|\s*"
*)
logical_or = {' '}, '||', { ' ' };
range      = hyphen | simple, { ' ', simple} | '';
hyphen     = partial, ' - ', partial;
simple     = primitive | partial | tilde | caret;

(*

*)
primitive  = ( '<' | '>' | '>=' | '<=' | '=' ), partial;
partial    = xr, ( '.', xr ( '.', xr, qualifier ? )? )?;
xr         = 'x' | 'X' | '*' | nr;

(*
r"0|[1-9]\d*"
*)
nr         = '0' | ['1'-'9'] { ['0'-'9'] };
tilde      = '~', partial;
caret      = '^', partial;
qualifier  = ( '-', pre )?, ( '+', build )?;
pre        = parts;
build      = parts;
parts      = part, { '.', part };
part       = nr | [-0-9A-Za-z]+;